In [6]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing data
data = pd.read_csv("C:/Users/Abhi/Desktop/Salary.csv")

In [7]:
# 1) Initialise variable
X = data['YearsExperience'].values.reshape(-1,1)
y = data['Salary'].values.reshape(-1,1)

In [8]:
# 2) Splitting data set into training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)


In [9]:
# 3) Fitting linear regression to our training set to train our model
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [10]:
# 4) Predicting the test result 
y_pred = reg.predict(X_test)

In [11]:
# 5) Checking accuracy
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9024461774180497

In [12]:
# 6) Output result for given input
output = reg.predict([[5.2]])
output

array([[74325.42269154]])

In [13]:
#  7) Intercept
reg.intercept_

array([25321.58301178])

In [14]:
reg.coef_

array([[9423.81532303]])

In [25]:
# Prediction for new values
experience = float(input("Enter the year of experience: "))

# Predicting salary with respect to years of experience

output = reg.predict([[experience]])
print(output)

Enter the year of experience: 5.2
[[74325.42269154]]
